### ISSUE TITLE
Undefined error

### ISSUE THREAD

**Issue by Californ1a** [Frederisk/Wikitext-Extension-Gadget#1]
I can use the local wikitext extension just fine, log in and pull page from the F1 menu inside vscode:

![](https://i.imgur.com/gWKeuw3.png)

However, when using this script from releases put into my common.js and hitting the open in vscode button, I get an undefined error, with no more info in it:

![](https://i.imgur.com/dxpN9dA.png)

**Comment by Frederisk** [comment]
Is the site you are logging in private?  In other words, you need to log in before you can browse the page or use the API?

**Comment by Californ1a** [comment]
No, and I've tried multiple sites with the same result. Both https://distance.fandom.com/ and https://runescape.wiki/ give that undefined error. The successful notifications from the first screenshot are from https://distance.fandom.com/ by using the F1 menu directly in VSCode (it also works fine on https://runescape.wiki/ if I use it directly in VSCode), but when I put the script [in my common.js](https://distance.fandom.com/wiki/User:Californ1a/common.js) and hit the "Open in VSCode" button, then I get the undefined error.
