### ISSUE TITLE
bug: odd styling on Vector 2022

### ISSUE THREAD

**Issue by Rexogamer** [Frederisk/Wikitext-Extension-Gadget#5]
The link seems to float?
![164BDBA5-350A-4EF9-B301-CEA9CD4D5E83](https://user-images.githubusercontent.com/42586271/195680461-12b9288f-b71b-46f9-904c-78dcccc6721c.jpeg)

**Comment by Frederisk** [comment]
Please describe your environment more clearly, such as which new Vector.

**Comment by Frederisk** [comment]
<https://phabricator.wikimedia.org/T320691>

**Comment by Rexogamer** [comment]
Fixed upstream :tada:
